# (c) 2019, Remko Deenik (rdeenik@purestorage.com)
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
#
# Description:
# This ansible-playbook will create a volume copy on a remote array using protection groups
# It assumes the following:
# - a protection group has been created on the source array;
# - the target FlashArray is added to the protection group.
# The playbook will create a snapshot, which is replicated and copied to a new volume,
# after the copy the snapshots are removed from both the source and target.
#
# Change the 'vars:' section below with the correct IP address, API token for the source/target arrays
# and change the name of the source protectiongroup and source volume.
#
# The playbook uses jquery which requires jmespath, make sure these are installed
# use 'pip install jmespath' to install. This playbook requires Ansible version 2.9 to run.
#
- name: Create a remote copy of a volume using it's protection group
  hosts: localhost
  gather_facts: yes
  vars:
    fa_url_source: 10.1.1.50                                    # IP address of URL to source FlashArray
    fa_api_token_source: 0a805297-ac78-88fc-a520-7b9e70b8ef74   # API token used for source FlashArray
    source_pg: mysqldemo                                        # Protection group name
    source_vol: vvol-mysql-b4ec20d1-vg/Data-e0e1b633            # Volume name
    fa_url_target: 10.1.1.70                                    # IP address of URL to target FlashArray
    fa_api_token_target: 09ce30f6-7422-700c-1706-25beddd05325   # API token used for target FlashArray
  tasks:
  - name: "Collect information of the source Pure Storage FlashArray ({{ fa_url_source }})"
    purefa_facts:
      fa_url: "{{ fa_url_source }}"
      api_token: "{{ fa_api_token_source }}"
  - set_fact:
      fa_host_source: "{{ ansible_facts['purefa_facts']['default']['array_name'] }}"
  - name: "Collect information of the target Pure Storage FlashArray ({{ fa_url_target }})"
    purefa_facts:
      fa_url: "{{ fa_url_target }}"
      api_token: "{{ fa_api_token_target }}"
  - set_fact:
      fa_host_target: "{{ ansible_facts['purefa_facts']['default']['array_name'] }}"
      snapshot_name: "{{ ansible_facts['date_time']['iso8601_basic_short'] }}"
  - debug: 
      msg: 
      - "Working with FlashArray {{ fa_host_source }} and {{ fa_host_target }} and using snapshot name {{ snapshot_name }}"
  - name: "Create snd replicate snapshot on protection group {{ source_pg }}"
    purefa_pgsnap:
      name: "{{ source_pg }}"
      suffix: "{{ snapshot_name }}"
      state: present
      now: true
      apply_retention: true
      remote: true
      fa_url: "{{ fa_url_source }}"
      api_token: "{{ fa_api_token_source }}"
  - name: Wait until PG transfer is complete
    purefa_facts:
      gather_subset: pgroups
      api_token: "{{ fa_api_token_target }}"
      fa_url: "{{ fa_url_target }}"
    register: output
    retries: 10
    delay: 5
    ignore_errors: true
    until: "{{ output | json_query('ansible_facts.ansible_purefa_facts.pgroups.\"'+fa_host_source + ':' + source_pg+'\".snaps.\"'+fa_host_source + ':' + source_pg + '.' + snapshot_name+'\".progress') }} != 0.0"
  - name: "Create a new volume from the snapshot on {{ fa_host_target }}"
    purefa_pgsnap:
      name: "{{ fa_host_source }}:{{ source_pg }}"
      suffix: "{{ snapshot_name }}"
      state: copy
      restore: "{{ source_vol }}"
      overwrite: true
      fa_url: "{{ fa_url_target }}"
      api_token: "{{ fa_api_token_target }}"
  - name: "Remove temporary snapshot from {{ fa_host_source }}"
    purefa_pgsnap:
      name: "{{ source_pg }}"
      suffix: "{{ snapshot_name }}"
      eradicate: true
      fa_url: "{{ fa_url_source }}"
      api_token: "{{ fa_api_token_source }}"
      state: absent
  - name: "Remove temporary snapshot from {{ fa_host_target }}"
    purefa_pgsnap:
      name: "{{ fa_host_source }}:{{ source_pg }}"
      suffix: "{{ snapshot_name }}"
      eradicate: true
      fa_url: "{{ fa_url_target }}"
      api_token: "{{ fa_api_token_target }}"
      state: absent

