#cloud-config

# Create administrative user
users:
  - default
  - name: ${username}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ${public-key}

# Install required software packages
packages:
  - vim
  - net-tools
  - python3-pip
  - sh -c "touch /etc/cloud/cloud-init.done"