#cloud-config

# Create administrative user
users:
  - default
  - name: ${username}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ${public-key}

# Install required software packages
packages:
  - vim
  - net-tools
  - open-iscsi
  - multipath-tools

# Set the IP addresses
write_files:
  - content: |
      network:
          ethernets:
              ens192:
                  dhcp4: true
              ens224:
                  dhcp4: false
                  addresses: ${iscsi-ip-addr}
          version: 2
    path: /etc/netplan/50-cloud-init.yaml

# Activate network changes
runcmd:
  - netplan apply